GPU: '0' # -1 is CPU


BATCH_SIZE : 2
NUM_EPOCHS : 150

OPTIM:
  LR_INIT: 1e-5

# data
DATA_DIR : '../data/cropweed_total/CWFID/seg'
SAVE_DIR : './segtrain/CWFID'
NUM_CLASSES : 3
RESIZE : 512

# resume training
LOAD_WEIGHTS : ''
